# Generated by Django 5.2 on 2026-01-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
            ],
            options={
                'verbose_name': '著者',
                'verbose_name_plural': '著者',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='出版社名')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('isbn', models.CharField(max_length=17, unique=True, verbose_name='ISBN')),
                ('published_date', models.DateField(verbose_name='発売日')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.author', verbose_name='著者')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.publisher', verbose_name='出版社')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
            },
        ),
    ]
